<?php

return [

    'lebanon' => [
        // Beirut
        'Beirut' => ['en' => 'Beirut', 'ar' => 'بيروت'],

        // Mount Lebanon
        'Baabda' => ['en' => 'Baabda', 'ar' => 'بعبدا'],
        'Jdeideh' => ['en' => 'Jdeideh', 'ar' => 'جديدة'],
        'Choueifat' => ['en' => 'Choueifat', 'ar' => 'الشويفات'],
        'Aley' => ['en' => 'Aley', 'ar' => 'عاليه'],
        'Bikfaya' => ['en' => 'Bikfaya', 'ar' => 'بكفيا'],
        'Beit Mery' => ['en' => 'Beit Mery', 'ar' => 'بيت مري'],
        'Broummana' => ['en' => 'Broummana', 'ar' => 'برمانا'],
        'Bhamdoun' => ['en' => 'Bhamdoun', 'ar' => 'بحمدون'],
        'Zouk Mikael' => ['en' => 'Zouk Mikael', 'ar' => 'ذوق مكايل'],
        'Zouk Mosbeh' => ['en' => 'Zouk Mosbeh', 'ar' => 'ذوق مصبح'],
        'Antelias' => ['en' => 'Antelias', 'ar' => 'انطلياس'],
        'Dbayeh' => ['en' => 'Dbayeh', 'ar' => 'ضبيه'],
        'Hazmieh' => ['en' => 'Hazmieh', 'ar' => 'حازمية'],
        'Jounieh' => ['en' => 'Jounieh', 'ar' => 'جونية'],
        'Sarba' => ['en' => 'Sarba', 'ar' => 'صرما'],
        'Kaslik' => ['en' => 'Kaslik', 'ar' => 'كسليك'],
        'Ghosta' => ['en' => 'Ghosta', 'ar' => 'غوسطا'],
        'Ajaltoun' => ['en' => 'Ajaltoun', 'ar' => 'عجلتون'],
        'Rayfoun' => ['en' => 'Rayfoun', 'ar' => 'ريفون'],
        'Ballouneh' => ['en' => 'Ballouneh', 'ar' => 'بلونة'],
        'Araya' => ['en' => 'Araya', 'ar' => 'عرَيّا'],
        'Aramoun' => ['en' => 'Aramoun', 'ar' => 'عرمون'],
        'Qmatiyeh' => ['en' => 'Qmatiyeh', 'ar' => 'قماطية'],
        'Shemlan' => ['en' => 'Shemlan', 'ar' => 'شمّلان'],
        'Souk El Gharb' => ['en' => 'Souk El Gharb', 'ar' => 'سوق الغرب'],
        'Deir El Qamar' => ['en' => 'Deir El Qamar', 'ar' => 'دير القمر'],
        'Beiteddine' => ['en' => 'Beiteddine', 'ar' => 'بيت الدين'],
        'Mansourieh' => ['en' => 'Mansourieh', 'ar' => 'منصورية'],
        'Bsous' => ['en' => 'Bsous', 'ar' => 'بسوس'],
        'Kornet Chehwan' => ['en' => 'Kornet Chehwan', 'ar' => 'قرنة شهوان'],
        'Qornet El Hamra' => ['en' => 'Qornet El Hamra', 'ar' => 'قرنة الحمرا'],
        'Yarze' => ['en' => 'Yarze', 'ar' => 'يرزة'],
        'Naas' => ['en' => 'Naas', 'ar' => 'ناعس'],
        'Mtein' => ['en' => 'Mtein', 'ar' => 'المتن'],
        'Dik El Mehdi' => ['en' => 'Dik El Mehdi', 'ar' => 'ديك المهدي'],
        'Fanar' => ['en' => 'Fanar', 'ar' => 'فنار'],
        'Naccache' => ['en' => 'Naccache', 'ar' => 'نقاش'],
        'Jal El Dib' => ['en' => 'Jal El Dib', 'ar' => 'جل الديب'],
        'Barja' => ['en' => 'Barja', 'ar' => 'برجا'],

        // North Lebanon
        'Tripoli' => ['en' => 'Tripoli', 'ar' => 'طرابلس'],
        'Mina' => ['en' => 'Mina', 'ar' => 'الميناء'],
        'Baddawi' => ['en' => 'Baddawi', 'ar' => 'البداوي'],
        'Zgharta' => ['en' => 'Zgharta', 'ar' => 'زغرتا'],
        'Ehden' => ['en' => 'Ehden', 'ar' => 'إهدن'],
        'Batroun' => ['en' => 'Batroun', 'ar' => 'البترون'],
        'Amioun' => ['en' => 'Amioun', 'ar' => 'أميون'],
        'Bsharri' => ['en' => 'Bsharri', 'ar' => 'بشري'],
        'Chekka' => ['en' => 'Chekka', 'ar' => 'شكا'],
        'Qalamoun' => ['en' => 'Qalamoun', 'ar' => 'قلمون'],
        'Anfeh' => ['en' => 'Anfeh', 'ar' => 'أنفه'],
        'Deddeh' => ['en' => 'Deddeh', 'ar' => 'دده'],
        'Kousba' => ['en' => 'Kousba', 'ar' => 'كوسبا'],
        'Barhalyoun' => ['en' => 'Barhalyoun', 'ar' => 'برحليون'],
        'Sir El Dinnieh' => ['en' => 'Sir El Dinnieh', 'ar' => 'سير الضنية'],
        'Bechmezzine' => ['en' => 'Bechmezzine', 'ar' => 'بشمزين'],
        'Tannourine' => ['en' => 'Tannourine', 'ar' => 'تنورين'],
        'Miziara' => ['en' => 'Miziara', 'ar' => 'مزيارة'],
        'Mazraat El Toufah' => ['en' => 'Mazraat El Toufah', 'ar' => 'مزرعة التفاح'],

        // Akkar
        'Halba' => ['en' => 'Halba', 'ar' => 'حلبا'],
        'Qoubaiyat' => ['en' => 'Qoubaiyat', 'ar' => 'القبيات'],
        'Bebnine' => ['en' => 'Bebnine', 'ar' => 'ببنين'],
        'Mhammara' => ['en' => 'Mhammara', 'ar' => 'المحمّرة'],
        'Berqayel' => ['en' => 'Berqayel', 'ar' => 'برقايل'],
        'Fnaideq' => ['en' => 'Fnaideq', 'ar' => 'فنيدق'],
        'El Koueikhate' => ['en' => 'El Koueikhate', 'ar' => 'الكوَيخات'],
        'Wadi Khaled' => ['en' => 'Wadi Khaled', 'ar' => 'وادي خالد'],
        'Ain Yaaqoub' => ['en' => 'Ain Yaaqoub', 'ar' => 'عين يعقوب'],
        'Meshmesh' => ['en' => 'Meshmesh', 'ar' => 'مشمش'],
        'Andaket' => ['en' => 'Andaket', 'ar' => 'عندقت'],
        'Deir Jannine' => ['en' => 'Deir Jannine', 'ar' => 'دير جنين'],
        'Tleil' => ['en' => 'Tleil', 'ar' => 'تلّيل'],
        'Tebnine' => ['en' => 'Tebnine', 'ar' => 'تبنين'],
        'Qochloq' => ['en' => 'Qochloq', 'ar' => 'قشلق'],

        // South Lebanon
        'Sidon' => ['en' => 'Sidon', 'ar' => 'صيدا'],
        'Jezzine' => ['en' => 'Jezzine', 'ar' => 'جزين'],
        'Sarafand' => ['en' => 'Sarafand', 'ar' => 'صرفند'],
        'Zahrani' => ['en' => 'Zahrani', 'ar' => 'الزهراني'],
        'Ghaziyeh' => ['en' => 'Ghaziyeh', 'ar' => 'غازية'],
        'Maghdouche' => ['en' => 'Maghdouche', 'ar' => 'مغدوشة'],
        'Kfarhatta' => ['en' => 'Kfarhatta', 'ar' => 'كفرحتى'],
        'Ain El Delb' => ['en' => 'Ain El Delb', 'ar' => 'عين الدلب'],
        'Qana' => ['en' => 'Qana', 'ar' => 'قانا'],
        'Tyre' => ['en' => 'Tyre', 'ar' => 'صور'],
        'Abbassieh' => ['en' => 'Abbassieh', 'ar' => 'العباسية'],
        'Borj El Chemali' => ['en' => 'Borj El Chemali', 'ar' => 'برج الشمالي'],
        'Rmeileh' => ['en' => 'Rmeileh', 'ar' => 'رميلة'],
        'Jbaa' => ['en' => 'Jbaa', 'ar' => 'جباع'],
        'Kfar Melki' => ['en' => 'Kfar Melki', 'ar' => 'كفرملكي'],
        'Ain Ebel' => ['en' => 'Ain Ebel', 'ar' => 'عين إبل'],
        'Rachaya El Foukhar' => ['en' => 'Rachaya El Foukhar', 'ar' => 'راشيا الفخار'],
        'Deir Qanoun En Nahr' => ['en' => 'Deir Qanoun En Nahr', 'ar' => 'دير قانون النهر'],
        'Srifa' => ['en' => 'Srifa', 'ar' => 'صُريفا'],
        'Aadloun' => ['en' => 'Aadloun', 'ar' => 'عدلون'],
        'Qlayaa' => ['en' => 'Qlayaa', 'ar' => 'قليعة'],

        // Nabatieh
        'Nabatieh' => ['en' => 'Nabatieh', 'ar' => 'النبطية'],
        'Bint Jbeil' => ['en' => 'Bint Jbeil', 'ar' => 'بنت جبيل'],
        'Marjayoun' => ['en' => 'Marjayoun', 'ar' => 'مرجعيون'],
        'Hasbaya' => ['en' => 'Hasbaya', 'ar' => 'حاصبيا'],
        'Khiam' => ['en' => 'Khiam', 'ar' => 'الخيام'],
        'Ainata' => ['en' => 'Ainata', 'ar' => 'عيناتا'],
        'Kfarkela' => ['en' => 'Kfarkela', 'ar' => 'كفركلا'],
        'Deir Mimas' => ['en' => 'Deir Mimas', 'ar' => 'دير ميماس'],
        'Houla' => ['en' => 'Houla', 'ar' => 'حولا'],
        'Yater' => ['en' => 'Yater', 'ar' => 'ياتر'],
        'Ain Qana' => ['en' => 'Ain Qana', 'ar' => 'عين قانا'],
        'Kfour' => ['en' => 'Kfour', 'ar' => 'كفور'],
        'Zawtar' => ['en' => 'Zawtar', 'ar' => 'زوطر'],
        'Mazraat En Naher' => ['en' => 'Mazraat En Naher', 'ar' => 'مزرعة النهر'],

        // Beqaa
        'Zahle' => ['en' => 'Zahle', 'ar' => 'زحلة'],
        'Chtaura' => ['en' => 'Chtaura', 'ar' => 'شتورا'],
        'Baalbek' => ['en' => 'Baalbek', 'ar' => 'بعلبك'],
        'Rayak' => ['en' => 'Rayak', 'ar' => 'رياق'],
        'Taanayel' => ['en' => 'Taanayel', 'ar' => 'تعنايل'],
        'Anjar' => ['en' => 'Anjar', 'ar' => 'عنجر'],
        'Ferzol' => ['en' => 'Ferzol', 'ar' => 'فرزل'],
        'Qabb Ilyas' => ['en' => 'Qabb Ilyas', 'ar' => 'قب إلياس'],
        'Majdal Anjar' => ['en' => 'Majdal Anjar', 'ar' => 'مجدل عنجر'],
        'Niha' => ['en' => 'Niha', 'ar' => 'نيحا'],
        'Riyaq' => ['en' => 'Riyaq', 'ar' => 'رياق'],
        'Bar Elias' => ['en' => 'Bar Elias', 'ar' => 'بر الياس'],
        'Kfarzabad' => ['en' => 'Kfarzabad', 'ar' => 'كفرزبد'],
        'Ali El Nahri' => ['en' => 'Ali El Nahri', 'ar' => 'علي النهري'],
        'Deir El Ahmar' => ['en' => 'Deir El Ahmar', 'ar' => 'دير الأحمر'],
        'Jdita' => ['en' => 'Jdita', 'ar' => 'جدَيتا'],
        'Houch El Ghanam' => ['en' => 'Houch El Ghanam', 'ar' => 'حوش الغنم'],
        'Saadnayel' => ['en' => 'Saadnayel', 'ar' => 'سعدنايل'],
        'Taalabaya' => ['en' => 'Taalabaya', 'ar' => 'تعلبايا'],

        // Baalbek-Hermel
        'Hermel' => ['en' => 'Hermel', 'ar' => 'الهرمل'],
        'Ras Baalbek' => ['en' => 'Ras Baalbek', 'ar' => 'رأس بعلبك'],
        'Labweh' => ['en' => 'Labweh', 'ar' => 'اللبوة'],
        'Al Ain' => ['en' => 'Al Ain', 'ar' => 'العين'],
        'Fakiha' => ['en' => 'Fakiha', 'ar' => 'الفاكهة'],
        'Qaa' => ['en' => 'Qaa', 'ar' => 'القاع'],
        'Younine' => ['en' => 'Younine', 'ar' => 'يونين'],
        'Ain Bourday' => ['en' => 'Ain Bourday', 'ar' => 'عين بورضاي'],
        'Chlifa' => ['en' => 'Chlifa', 'ar' => 'شليفا'],
        'Nabi Chit' => ['en' => 'Nabi Chit', 'ar' => 'نبي شيت'],
        'Nahle' => ['en' => 'Nahle', 'ar' => 'نحلة'],
        'Tfail' => ['en' => 'Tfail', 'ar' => 'طفيل'],
        'Britel' => ['en' => 'Britel', 'ar' => 'بريتال'],
    ],

];
